### PR TITLE
Benefit section completed with responsive.

### PR DESCRIPTION
**Pull request by DeathKnight813**
Benefit section completed with responsive.
from Robert.

### CODE REVIEW

**Review by prodbyola — CHANGES_REQUESTED** [review]
Wow, this is amazing @DeathKnight813. Thank you for the contribution. We only need to fix a few thing.

* Avoid horizontal overflow on mobile devices. Please see attached video.
* On mobile devices, we need the first item to be placed at the center. I understand that the initial item seem aligned to the left on the original figma design. This is to show that the component is swipeable. We have to make first item align to the center (before swipe) in order to prevent the component from appearing out of order.

I look forward to merging this PR. Thank you. 

https://github.com/user-attachments/assets/916a99c2-bc99-4011-a91b-9217275fc754

**Comment by DeathKnight813** [comment]
I already completed first issue.
And I will complete second issue too asap.

**Comment by DeathKnight813** [comment]
https://github.com/user-attachments/assets/6ecea750-d50a-4057-9a4e-30f6e8b50ab1

**Comment by DeathKnight813** [comment]
All of issues completed!
Please check this PR.

**Review by prodbyola — APPROVED** [review]

**Pull request merged**
