### PR TITLE
Added Features Section

### PR DESCRIPTION
**Pull request by Samson-bot-ai**

### CODE REVIEW

**Review by prodbyola — CHANGES_REQUESTED** [review]
Hi @Samson-bot-ai,
Thanks for your interest in contributing to Basable project, and for your efforts so far. I don't know if converting figma designs to images will become acceptable standard for web development in the nearest future. Unfortunately, we cannot merge this PR as it is right now. You need to code out the different components, as opposed to converting them to images. 

I hope you're able to fix soon. Thank you.

**Comment by Samson-bot-ai** [comment]
Noted.
I will make the changes ASAP.
Thanks

**Comment by Samson-bot-ai** [comment]
Please review the changes.
thanks

**Review by prodbyola — APPROVED** [review]
Great @Samson-bot-ai! Will merge this very soon. Though there are a few changes required. They're minor and I'll fix them from here. Thank you for your contributions.

**Comment by Samson-bot-ai** [comment]
Alright.
Let me know if you need me to do anything.

**Pull request merged**
